/**
 * Filesystem contents for the virtual shell.
 * Returns a nested object: directories are objects, files are strings.
 * The MegaCorp app is a Node.js/Express API — modern JS, not PHP.
 */

function buildFilesystem() {
  return {
    etc: {
      hostname: 'megacorp-web-01',
      hosts: '127.0.0.1\tlocalhost\n10.0.1.50\tdb.internal\n10.0.1.10\tmail.internal',
      passwd: [
        'root:x:0:0:root:/root:/bin/bash',
        'www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin',
        'postgres:x:26:26:PostgreSQL Server:/var/lib/pgsql:/bin/bash',
        'admin:x:1000:1000:MegaCorp Admin:/home/admin:/bin/bash',
        'jsmith:x:1001:1001:John Smith:/home/jsmith:/bin/bash',
      ].join('\n'),
      'resolv.conf': 'nameserver 10.0.1.1\nsearch megacorp.local',
      crontab: '# MegaCorp crontab\n0 2 * * * /usr/local/bin/backup.sh\n*/5 * * * * /usr/local/bin/health-check.sh',
      secrets: {
        'api_keys.txt': [
          '# MegaCorp Production API Keys',
          '# Last rotated: 2024-01-15 (overdue!)',
          '',
          'AWS_SECRET_KEY=AKIA3R9F8GHSL29XKMP4',
          'STRIPE_LIVE_KEY=sk_live_4eC39HqLyjWDarjtT1',
          'DATABASE_URL=postgres://admin:S3cretP@ss!@prod-db:5432/megacorp',
          'SLACK_WEBHOOK=https://hooks.slack.com/services/T0DEADBEEF/B0DEADBEEF/xyzzy',
        ].join('\n'),
      },
    },
    var: {
      www: {
        megacorp: {
          'package.json': [
            '{',
            '  "name": "megacorp-portal",',
            '  "version": "1.0.0",',
            '  "description": "MegaCorp Employee Portal",',
            '  "main": "server.js",',
            '  "dependencies": {',
            '    "express": "^4.21.0",',
            '    "better-sqlite3": "^11.7.0",',
            '    "child_process": "^1.0.2"',
            '  }',
            '}',
          ].join('\n'),
          'server.js': [
            'const express = require("express");',
            'const db = require("./db");',
            'const routes = require("./routes");',
            '',
            'const app = express();',
            'app.use(express.json());',
            'app.use(express.urlencoded({ extended: true }));',
            '',
            '// Serve the frontend',
            'app.use(express.static("public"));',
            '',
            '// Mount API routes',
            'app.use(routes);',
            '',
            'app.listen(3000, () => {',
            '  console.log("MegaCorp Portal running on http://localhost:3000");',
            '});',
          ].join('\n'),
          'db.js': [
            'const Database = require("better-sqlite3");',
            'const path = require("path");',
            '',
            '// Connect to SQLite database',
            'const db = new Database(path.join(__dirname, "../../../var/lib/megacorp/megacorp.db"));',
            '',
            '// Database credentials (also in /etc/secrets/api_keys.txt)',
            '// DB_USER: megacorp_app',
            '// DB_PASS: mc_db_2024!',
            '',
            'module.exports = db;',
          ].join('\n'),
          'routes.js': [
            'const express = require("express");',
            'const { execSync } = require("child_process");',
            'const db = require("./db");',
            'const router = express.Router();',
            '',
            '// ============================================================',
            '// GET /login',
            '// Serves the login page.',
            '// ============================================================',
            'router.get("/login", (req, res) => {',
            '  // TODO: remove this before production!!!',
            '  // <!-- default test account: admin / password123 -->',
            '  res.send(`',
            '    <h1>MegaCorp Employee Portal</h1>',
            '    <!-- default test account: admin / password123 -->',
            '    <form method="POST" action="/login">',
            '      <input name="user" placeholder="Username" />',
            '      <input name="pass" type="password" placeholder="Password" />',
            '      <button type="submit">Sign In</button>',
            '    </form>',
            '  `);',
            '});',
            '',
            '// ============================================================',
            '// POST /login',
            '// Authenticates a user with parameterized query (safe).',
            '// ============================================================',
            'router.post("/login", (req, res) => {',
            '  const { user, pass } = req.body;',
            '  const row = db.prepare("SELECT * FROM users WHERE username = ? AND password = ?").get(user, pass);',
            '  if (row) {',
            '    res.json({ success: true, user: row.username, role: row.role });',
            '  } else {',
            '    res.status(401).json({ error: "Invalid credentials" });',
            '  }',
            '});',
            '',
            '// ============================================================',
            '// GET /api/employees/:id',
            '// Returns employee profile by ID.',
            '// NOTE: No authorization check — any user can view any profile!',
            '// TODO: add permission check before release',
            '// ============================================================',
            'router.get("/api/employees/:id", (req, res) => {',
            '  const id = parseInt(req.params.id);',
            '  const user = db.prepare("SELECT * FROM users WHERE id = ?").get(id);',
            '  if (!user) return res.status(404).json({ error: "Employee not found" });',
            '  res.json(user);',
            '});',
            '',
            '// ============================================================',
            '// GET /api/search?q=TERM',
            '// Searches employee directory. Results are rendered into HTML.',
            '// ============================================================',
            'router.get("/api/search", (req, res) => {',
            '  const q = req.query.q || "";',
            '  const rows = db.prepare(',
            '    "SELECT username, email, department FROM users WHERE username LIKE ? OR department LIKE ?"',
            '  ).all(`%${q}%`, `%${q}%`);',
            '',
            '  // BUG: User input is inserted directly into HTML without escaping!',
            '  const html = `',
            '    <h1>Employee Directory</h1>',
            '    <p>Showing results for: ${q}</p>',
            '    <table>${rows.map(r => `<tr><td>${r.username}</td><td>${r.email}</td></tr>`).join("")}</table>',
            '  `;',
            '  res.send(html);',
            '});',
            '',
            '// ============================================================',
            '// POST /api/admin/login',
            '// Admin login — VULNERABLE: uses string concatenation for SQL!',
            '// ============================================================',
            'router.post("/api/admin/login", (req, res) => {',
            '  const { user, pass } = req.body;',
            '',
            '  // VULNERABLE: string concatenation instead of parameterized query!',
            '  const query = `SELECT * FROM users WHERE username=\'${user}\' AND password=\'${pass}\'`;',
            '  try {',
            '    const rows = db.prepare(query).all();',
            '    if (rows.length > 0) {',
            '      res.json({ success: true, user: rows[0].username, role: rows[0].role });',
            '    } else {',
            '      res.status(401).json({ error: "Access denied" });',
            '    }',
            '  } catch (err) {',
            '    // Oops — leaking SQL errors to the client',
            '    res.status(500).json({ error: err.message, query });',
            '  }',
            '});',
            '',
            '// ============================================================',
            '// GET /api/diagnostic?host=HOST',
            '// Server health check — pings a host.',
            '// VULNERABLE: user input passed directly to shell command!',
            '// ============================================================',
            'router.get("/api/diagnostic", (req, res) => {',
            '  const host = req.query.host;',
            '  if (!host) return res.json({ error: "Please provide a host parameter" });',
            '',
            '  // VULNERABLE: user input goes directly into shell command!',
            '  const cmd = `ping -c 1 ${host}`;',
            '  try {',
            '    const output = execSync(cmd, { timeout: 5000 }).toString();',
            '    res.json({ command: cmd, output });',
            '  } catch (err) {',
            '    res.json({ command: cmd, output: err.stdout?.toString() || err.message });',
            '  }',
            '});',
            '',
            'module.exports = router;',
          ].join('\n'),
          public: {
            'index.html': [
              '<!DOCTYPE html>',
              '<html>',
              '<head><title>MegaCorp Portal</title></head>',
              '<body>',
              '  <h1>Welcome to MegaCorp</h1>',
              '  <nav>',
              '    <a href="/login">Login</a> |',
              '    <a href="/api/employees/1">My Profile</a> |',
              '    <a href="/api/search?q=">Employee Search</a> |',
              '    <a href="/api/diagnostic?host=localhost">Server Diagnostics</a>',
              '  </nav>',
              '</body>',
              '</html>',
            ].join('\n'),
          },
          node_modules: {
            '.package-lock.json': '{ "lockfileVersion": 3 }',
          },
          '.env': [
            '# MegaCorp environment variables',
            'PORT=3000',
            'DB_PATH=/var/lib/megacorp/megacorp.db',
            'SESSION_SECRET=megacorp_secret_key_do_not_share',
          ].join('\n'),
        },
      },
      log: {
        nginx: {
          'access.log': [
            '10.0.1.100 - admin [15/Jan/2025:09:15:23 +0000] "GET /api/employees/4 HTTP/1.1" 200 1532',
            '10.0.1.100 - admin [15/Jan/2025:09:15:45 +0000] "GET /api/diagnostic?host=localhost HTTP/1.1" 200 892',
            '10.0.1.55 - jsmith [15/Jan/2025:09:22:10 +0000] "GET /api/employees/1 HTTP/1.1" 200 1204',
            '10.0.1.55 - jsmith [15/Jan/2025:09:22:15 +0000] "GET /api/search?q=wilson HTTP/1.1" 200 756',
            '10.0.1.200 - - [15/Jan/2025:10:01:33 +0000] "POST /login HTTP/1.1" 401 52',
            '10.0.1.200 - - [15/Jan/2025:10:01:45 +0000] "POST /login HTTP/1.1" 401 52',
            '10.0.1.200 - - [15/Jan/2025:10:02:01 +0000] "POST /login HTTP/1.1" 200 1532',
          ].join('\n'),
          'error.log': [
            '[Wed Jan 15 10:01:33 2025] [error] [client 10.0.1.200] Authentication failed for user: root',
            '[Wed Jan 15 10:01:45 2025] [error] [client 10.0.1.200] Authentication failed for user: administrator',
            '[Thu Jan 16 03:14:22 2025] [warn] SqliteError: near "\'": syntax error — POST /api/admin/login',
          ].join('\n'),
        },
        'auth.log': [
          'Jan 15 10:01:33 megacorp-web-01 sshd[1234]: Failed password for root from 10.0.1.200 port 44322 ssh2',
          'Jan 15 10:01:45 megacorp-web-01 sshd[1235]: Failed password for admin from 10.0.1.200 port 44323 ssh2',
          'Jan 15 10:02:01 megacorp-web-01 sshd[1236]: Accepted password for admin from 10.0.1.200 port 44324 ssh2',
          'Jan 16 02:00:00 megacorp-web-01 CRON[5678]: pam_unix(cron:session): session opened for user root',
        ].join('\n'),
      },
      lib: {
        megacorp: {
          'megacorp.db': '[SQLite 3 database — use sqlite3 command to open]',
        },
      },
    },
    home: {
      admin: {
        '.bash_history': [
          'cd /var/www/megacorp',
          'cat routes.js',
          'sqlite3 /var/lib/megacorp/megacorp.db "SELECT * FROM users"',
          'cat /etc/secrets/api_keys.txt',
          'curl http://localhost:3000/api/diagnostic?host=localhost',
          'pm2 restart megacorp',
        ].join('\n'),
        'notes.txt': [
          'TODO List (admin):',
          '- Remove test account credentials from login page HTML',
          '- Fix /api/employees/:id to check user permissions before returning data',
          '- Sanitize search input on /api/search (Karen reported weird HTML showing up)',
          '- Switch /api/admin/login to use parameterized queries like /login',
          '- Restrict /api/diagnostic to admin IPs only',
          '- Rotate API keys in /etc/secrets/ (last rotated 6+ months ago!)',
        ].join('\n'),
        '.ssh': {
          'authorized_keys': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ... admin@megacorp',
        },
      },
      jsmith: {
        '.bash_history': 'ls\npwd\nwhoami',
        'readme.txt': 'Welcome to MegaCorp! Your profile is at http://localhost:3000/api/employees/1',
      },
      'www-data': {},
    },
    tmp: {
      'debug.log': 'MegaCorp Debug Log\n[2025-01-15 09:00:00] Server started\n[2025-01-15 09:15:23] Admin login from 10.0.1.100\n[2025-01-16 03:14:22] SqliteError in /api/admin/login — possible injection attempt?',
    },
    proc: {
      version: 'Linux version 5.15.0-generic (buildd@lcy02-amd64-045) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0) #1 SMP x86_64',
    },
  };
}

module.exports = { buildFilesystem };
